name: Test action
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test digital ocean deploy app action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action (create)
        uses: ./ # Uses an action in the root directory
        id: test-action-create
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          spec: ./test/test-app.yaml
      - name: Test action (update existing)
        uses: ./ # Uses an action in the root directory
        id: test-action-update
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          spec: ./test/test-app.yaml
      - name: Install doctl for cleanup
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Cleanup created app
        run: |
          doctl app delete -f ${{ steps.test-action-create.outputs.app-id }}
